package viewdemo;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author zlatan
 */
public class MainFrame extends javax.swing.JFrame {
    TabPanel tp;
    private JPanel pane = null;
    private AddPanel ap=null;
    private DelPanel dp=null;
    private QueryPanel qp=null;
    private SearchPanel sp=null;
    private UpdatePanel up=null;
    private CardLayout card = null; // CardLayout布局管理器  
    private JButton addButton = null, delButton = null, queryButton = null,searchButton=null,updateButton=null; // 三个可直接翻转到JPanel组件的按钮

    public MainFrame() {
        //盛放各种功能的
        tp = new TabPanel();
        this.getContentPane().add(tp, BorderLayout.NORTH);
        //下面变得总得容器
        card = new CardLayout(5, 5);
        pane = new JPanel(card); // JPanel的布局管理将被设置成CardLayout
        ap=new AddPanel();
        dp=new DelPanel();
        qp=new QueryPanel();
        sp=new SearchPanel();
        up=new UpdatePanel();
        pane.add(ap, "add");
        pane.add(dp, "del");
        pane.add(qp, "query");
        pane.add(sp, "search");
        pane.add(up, "update");
        addButton=(JButton)tp.getComponent(0);
        delButton=(JButton)tp.getComponent(1);
        queryButton=(JButton)tp.getComponent(2);
        searchButton=(JButton)tp.getComponent(3);
        updateButton=(JButton)tp.getComponent(4);
        
        addButton.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                card.show(pane, "add");  
            }  
        });
        delButton.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                card.show(pane, "del");  
            }  
        });
        queryButton.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                card.show(pane, "query");  
            }  
        });
        searchButton.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                card.show(pane, "search");  
            }  
        });
        updateButton.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                card.show(pane, "update");  
            }  
        });
        
        
        
        
        this.getContentPane().add(pane);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        this.setSize(600,600);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("学生信息管理系统");
        setSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
